stages:
  - pre-build
  - build
  #- test
  - release
  #- deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE/jenkins:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/jenkins:latest
  JENKINS_USER: admin
  JENKINS_USER_PASSWORD: admin


prepare jenking init config:
  stage: pre-build
  image:
    name: aemdesign/ansible-playbook:latest
    entrypoint: [""]
  cache:
    key: jenkins-build-config
    paths:
      - build-config
  script:
    - mkdir -p build-config
    - jinja2 templates/init-create-user.groovy.j2 -D jenkins_admin_password=$JENKINS_USER -D jenkins_admin_username=$JENKINS_USER_PASSWORD > build-config/init-create-user.groovy

build docker image:
  stage: build
  image:
    name: docker:stable
  services:
    - docker:dind
  cache:
    key: jenkins-build-config
    paths:
      - build-config
    policy: pull

  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

  script:
    - docker build --pull -t "$CONTAINER_TEST_IMAGE" .
    - docker push "$CONTAINER_TEST_IMAGE"
#
#test1:
#  stage: test
#  script:
#    - docker pull $CONTAINER_TEST_IMAGE
#    - docker run $CONTAINER_TEST_IMAGE /script/to/run/tests
#
#test2:
#  stage: test
#  script:
#    - docker pull $CONTAINER_TEST_IMAGE
#    - docker run $CONTAINER_TEST_IMAGE /script/to/run/another/test

release image:
  stage: release
  image: docker:stable
  services:
    - docker:dind

  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

  script:
    - docker pull "$CONTAINER_TEST_IMAGE"
    - docker tag "$CONTAINER_TEST_IMAGE" "$CONTAINER_RELEASE_IMAGE"
    - docker push "$CONTAINER_RELEASE_IMAGE"
  only:
    - master
#
#deploy:
#  stage: deploy
#  script:
#    - ./deploy.sh
#  only:
#    - master