language: java

if: tag is blank

services:
  - 'docker'

before_install:
  - "source <(curl -sL https://github.com/aem-design/aemdesign-docker/releases/latest/download/get_config.sh)"
  - "source <(curl -sL https://github.com/aem-design/aemdesign-docker/releases/latest/download/get_version.sh)"

#build and test
install:
  - echo CREATE JENKINS CONFIG
  - mvn dependency:copy-dependencies -DoutputDirectory=. --settings settings.xml
  - unzip vault-cli-$VAULT_VERSION-bin.zip
  - git clone https://github.com/aem-design/aemdesign-jenkins.git
  - mkdir ./build-config
  - docker run --rm -v $(pwd)/build-config:/data/build-config -v $(pwd)/templates:/data/templates -e JENKINS_USER=$JENKINS_USER -e JENKINS_USER_PASSWORD=$JENKINS_USER_PASSWORD --entrypoint="" aemdesign/ansible-playbook:latest bash -c "jinja2 /data/templates/init-create-user.groovy.j2 -D jenkins_admin_password=$JENKINS_USER_PASSWORD -D jenkins_admin_username=$JENKINS_USER > /data/build-config/init-create-user.groovy"
  - docker build --pull -t $IMAGE:$IMAGE_VERSION --build-arg VAULT_VERSION=${VAULT_VERSION} .
  - "source <(curl -sL https://github.com/aem-design/aemdesign-docker/releases/latest/download/container_verify.sh)"
  - docker images

#test
script:
  - echo "LOGIN TO HUB.DOCKER"
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - echo "PUSH HUB.DOCKER"
  - docker push $IMAGE:$IMAGE_VERSION
  - if [[ $TRAVIS_BRANCH == "master" ]]; then docker tag $IMAGE:$IMAGE_VERSION $IMAGE:latest && docker push $IMAGE:latest; fi
  - echo "UPDATE README IN HUB.DOCKER"
  - if [[ $TRAVIS_BRANCH == "master" ]]; then docker run --rm -v $(pwd):/data/ aemdesign/dockerhub-description "$DOCKER_USERNAME" "$DOCKER_PASSWORD" "$IMAGE"; fi

## Get the project version
before_deploy:
  - if [[ $TRAVIS_BRANCH == "master" ]]; then git tag $TRAVIS_TAG; fi

## Create release in GitHub
deploy:
  provider: releases
  tag_name: $TRAVIS_TAG
  name: $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    branch: master
