devops/jenkins:
  build: .
  labels:
    os.version: "centos"
    java.version: "oracle jdk 8"
    container.description: "extended Jenkins image to allow configuration during image build"
  container_name: "jenkins"
  ports:
   - "8080:8080"
   - "50000:50000"
  environment:
    - JENKINS_HOME=/var/jenkins_home
    - JENKINS_SLAVE_AGENT_PORT=50000
#  volumes:
#   - /var/jenkins_home:/var/jenkins_home
#  volumes_from:
#    - jenkins-data

